### ISSUE TITLE
mate post the src?

### ISSUE THREAD

**Issue by master7720** [XenoClientDevelopment/Xeno-Client#2]

**Comment by master7720** [comment]
WebConnectionCheck: {
	WARN: Found connection in javafx/fxml/FXMLLoader
	WARN: Found connection in com/sun/javafx/iio/common/ImageTools
	WARN: Found connection in javafx/scene/text/Font
	WARN: Found connection in com/sun/media/jfxmedia/locator/ConnectionHolder$URIConnectionHolder
	WARN: Found connection in com/sun/media/jfxmedia/locator/ConnectionHolder$URIConnectionHolder
	WARN: Found connection in com/sun/media/jfxmedia/locator/ConnectionHolder$URIConnectionHolder
	WARN: Found connection in com/sun/media/jfxmedia/locator/ConnectionHolder$URIConnectionHolder
	WARN: Found connection in com/sun/media/jfxmedia/locator/ConnectionHolder$URIConnectionHolder
	WARN: Found connection in com/sun/media/jfxmedia/locator/ConnectionHolder$URIConnectionHolder
	WARN: Found connection in com/sun/javafx/css/StyleManager
	WARN: Found connection in com/sun/media/jfxmedia/locator/HLSConnectionHolder$PlaylistParser
	WARN: Found connection in com/sun/media/jfxmedia/locator/HLSConnectionHolder$PlaylistParser
	WARN: Found connection in com/sun/media/jfxmedia/locator/Locator
	WARN: Found connection in com/sun/media/jfxmedia/locator/Locator
	WARN: Found connection in com/sun/media/jfxmedia/locator/Locator
	WARN: Found connection in com/sun/media/jfxmedia/locator/Locator
	WARN: Found connection in com/sun/media/jfxmedia/locator/Locator
	WARN: Found connection in com/sun/media/jfxmedia/locator/Locator
	WARN: Found connection in com/sun/webkit/network/DirectoryURLConnection$DirectoryInputStream
	WARN: Found connection in com/sun/webkit/LocalizedStrings$EncodingResourceBundleControl
	WARN: Found connection in javafx/fxml/FXMLLoader$ScriptElement
	WARN: Found connection in com/sun/javafx/tk/Toolkit
	WARN: Found connection in com/sun/javafx/tk/Toolkit
	WARN: Found connection in com/sun/javafx/runtime/async/AbstractRemoteResource
	WARN: Found connection in com/sun/javafx/runtime/async/AbstractRemoteResource
	WARN: Found connection in com/sun/javafx/runtime/async/AbstractRemoteResource
	WARN: Found connection in com/sun/media/jfxmedia/locator/HLSConnectionHolder
	WARN: Found connection in com/sun/javafx/css/parser/CSSParser
	WARN: Found connection in com/sun/webkit/network/SocketStreamHandle
	WARN: Found connection in com/sun/webkit/network/SocketStreamHandle
	WARN: Found connection in javafx/scene/web/WebEngine$2
	WARN: Found connection in com/sun/javafx/fxml/builder/JavaFXFontBuilder
	WARN: Found connection in com/sun/javafx/font/PrismFontLoader
	WARN: Found connection in com/sun/javafx/css/Stylesheet
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
	WARN: Found connection in com/sun/webkit/network/URLLoader
}
URLCheck: {
	WARN: Found URL [font-size : font-family : font-weight : font-style : FontConverter : Media Resou] in me/xenodevs/xeno/managers/EventManager
	WARN: Found URL [application/x-java-rawimage : text/uri-list : application/x-java-rawimage : text] in com/sun/javafx/tk/quantum/QuantumClipboard
	WARN: Found URL [application/x-java-rawimage : text/uri-list : application/x-java-rawimage : text] in com/sun/javafx/tk/quantum/QuantumClipboard
	WARN: Found URL [UTF-8 : controller : controller : charset is null. : Location is not set. : inpu] in javafx/fxml/FXMLLoader
	WARN: Found URL [0.5 : 0.5 : ArrayList : Displays the enabled modules on screen. : Direction : Fr] in com/sun/javafx/iio/common/ImageTools
	WARN: Found URL [Font[name= : , family= : , style= : , size= : ] : 17 : 37 : 37 : -1.0 : colors :] in javafx/scene/text/Font
	WARN: Found URL [about : data : specifyStreamHandler : WebEvent [source = %s, eventType = %s, dat] in com/sun/webkit/network/URLs
	WARN: Found URL [about : data : specifyStreamHandler : WebEvent [source = %s, eventType = %s, dat] in com/sun/webkit/network/URLs
	WARN: Found URL [about : data : specifyStreamHandler : WebEvent [source = %s, eventType = %s, dat] in com/sun/webkit/network/URLs
	WARN: Found URL [cannot writeBinary  : bad version  : Lcom/sun/javafx/css/SizeUnits; : AutoCrysta] in com/sun/javafx/css/ParsedValueImpl
	WARN: Found URL [AutoCrystal : best ca on the block. (skidded from Postman) : Break : Place : Swi] in com/sun/javafx/css/ParsedValueImpl
	WARN: Found URL [Including "%s" in "%s" created cyclic reference. : Controller : Scene - first re] in javafx/fxml/FXMLLoader$IncludeElement
	WARN: Found URL [Image loader: input stream == null : nativeiio : cycleCount : tickMarkVisible : ] in com/sun/javafx/iio/ios/IosImageLoader
	WARN: Found URL [/ : % : % : Missing resource key. : % : % : No resources specified. : Resource "] in javafx/fxml/FXMLLoader$Element
	WARN: Found URL [java.vm.name : os.arch : arm : Embedded : javafx.platform.properties : javafx.pl] in com/sun/javafx/PlatformUtil
	WARN: Found URL [PID: :  TID: : ( : )  : waitUntilDone : notifyDone : dumpAsText =  : 
--------
F] in com/sun/javafx/webkit/drt/DumpRenderTree
	WARN: Found URL [/ : com/sun/javafx/scene/control/skin/modena/ : com/sun/javafx/scene/control/ski] in com/sun/javafx/css/converters/URLConverter
	WARN: Found URL [file : .jar : file : jar:file : !/ : URLType : Ljavafx/application/Application; ] in com/sun/javafx/css/converters/URLConverter
	WARN: Found URL [Script source already specified. : Page language not specified. : source : chars] in javafx/fxml/FXMLLoader$ScriptElement
	WARN: Found URL [msvcr120 : Error: failed to load msvcr120.dll :  : msvcp120 : Error: failed to l] in com/sun/javafx/tk/Toolkit
	WARN: Found URL [DEFAULT : CROSSHAIR : TEXT : WAIT : SW_RESIZE : SE_RESIZE : NW_RESIZE : NE_RESIZ] in javafx/scene/Cursor
	WARN: Found URL [border : background : padding : cannot set padding to null : snapToPixel : scale] in com/sun/javafx/runtime/async/AbstractRemoteResource
	WARN: Found URL [/ : Error in Zoom gesture recognition: unknown touch state:  : Error in Zoom ges] in com/sun/javafx/fxml/builder/URLBuilder
	WARN: Found URL [/ : Error in Zoom gesture recognition: unknown touch state:  : Error in Zoom ges] in com/sun/javafx/fxml/builder/URLBuilder
	WARN: Found URL [Error in Zoom gesture recognition: unknown touch state:  : Error in Zoom gesture] in com/sun/javafx/fxml/builder/URLBuilder
	WARN: Found URL [string : \\[uU](.{4}) : \b : \t : \n : \f : \r : \" : \\ : Ljavafx/scene/Scene$D] in com/moandjiezana/toml/StringValueReaderWriter
	WARN: Found URL [size : style :   : url : IntegerBinding [value:  : ] : IntegerBinding [invalid] ] in com/sun/javafx/fxml/builder/JavaFXFontBuilder
	WARN: Found URL [size : style :   : url : IntegerBinding [value:  : ] : IntegerBinding [invalid] ] in com/sun/javafx/fxml/builder/JavaFXFontBuilder
	WARN: Found URL [IntegerBinding [value:  : ] : IntegerBinding [invalid] : predicate : Value of se] in com/sun/javafx/fxml/builder/JavaFXFontBuilder
	WARN: Found URL [IntegerBinding [value:  : ] : IntegerBinding [invalid] : predicate : Value of se] in com/sun/javafx/fxml/builder/JavaFXFontBuilder
	WARN: Found URL [IntegerBinding [value:  : ] : IntegerBinding [invalid] : predicate : Value of se] in com/sun/javafx/fxml/builder/JavaFXFontBuilder
	WARN: Found URL [===== URL list :  : ===== : http.proxyHost : https.proxyHost : ftp.proxyHost : s] in com/sun/javafx/application/LauncherImpl
	WARN: Found URL [com.sun.deploy.services.ServiceManager : setService : os.name : Win : STANDALONE] in com/sun/javafx/application/LauncherImpl
	WARN: Found URL [Input stream must not be null : :  : ^\p{Alpha}[\p{Alnum}+.-]*:.*$ : Unknown win] in javafx/scene/image/Image
}
CommandCheck: {
	ALERT: Shell command executed in com/sun/deploy/uitoolkit/impl/fx/HostServicesFactory$StandaloneHostService
}
FileDeletionCheck: {
	WARN: Found file deletion in javafx/scene/web/WebEngine
	WARN: Found file deletion in com/sun/javafx/font/FontFileWriter$FontTracker$TempFileDeletionHook
	WARN: Found file deletion in com/sun/javafx/font/FontFileWriter
	WARN: Found file deletion in com/sun/javafx/font/FontFileWriter
	WARN: Found file deletion in com/sun/javafx/font/PrismFontFile$FileDisposer
	WARN: Found file deletion in com/sun/javafx/font/PrismFontFile
}
CoordCheck: {
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/Surround
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/Surround
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/player/EnemyUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/player/EnemyUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/render/Nametags
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/render/Nametags
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/render/Nametags
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/render/Nametags
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/combat/CrystalUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/combat/CrystalUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/combat/CrystalUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/combat/CrystalUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/combat/CrystalUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/combat/CrystalUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/Aura
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/Aura
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/Aura
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/Aura
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/Aura
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/Aura
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/Aura
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/combat/Aura
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/hole/HoleUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/hole/HoleUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/gui/GuiUtil$1
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/gui/GuiUtil$1
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/player/PlayerUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/player/PlayerUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/player/PlayerUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/player/PlayerUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockInteractionHelper
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockInteractionHelper
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockInteractionHelper
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockInteractionHelper
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityFakePlayer
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityFakePlayer
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityFakePlayer
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityFakePlayer
	WARN: X or Z coordinates grabbed(1.12.2) in me/wolfsurge/mixin/mixins/MixinEntityPlayerSP
	WARN: X or Z coordinates grabbed(1.12.2) in me/wolfsurge/mixin/mixins/MixinEntityPlayerSP
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityHelper
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityHelper
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/block/BlockUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/wolfsurge/mixin/mixins/MixinRenderEntityItem
	WARN: X or Z coordinates grabbed(1.12.2) in me/wolfsurge/mixin/mixins/MixinRenderEntityItem
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/RaytraceUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/render/RenderUtils3D
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/render/RenderUtils3D
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/render/RenderUtils3D
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/render/RenderUtils3D
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/render/RenderUtils3D
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/render/RenderUtils3D
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/render/RenderUtils3D
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/render/RenderUtils3D
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/entity/EntityUtil
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/MathsHelper
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/utils/other/MathsHelper
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/movement/NoFall
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/movement/NoFall
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/movement/NoFall
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/movement/NoFall
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/movement/NoFall
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/movement/NoFall
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/render/HoleESP
	WARN: X or Z coordinates grabbed(1.12.2) in me/xenodevs/xeno/module/modules/render/HoleESP
}

Overview:
	me/xenodevs/xeno/module/modules/render/Nametags: CoordCheck 
	com/sun/media/jfxmedia/locator/ConnectionHolder$URIConnectionHolder: WebConnectionCheck 
	com/sun/media/jfxmedia/locator/HLSConnectionHolder$PlaylistParser: WebConnectionCheck 
	me/wolfsurge/mixin/mixins/MixinEntityPlayerSP: CoordCheck 
	me/xenodevs/xeno/managers/EventManager: URLCheck 
	com/sun/webkit/network/SocketStreamHandle: WebConnectionCheck 
	com/sun/javafx/css/StyleManager: WebConnectionCheck 
	me/xenodevs/xeno/module/modules/combat/Surround: CoordCheck 
	me/xenodevs/xeno/module/modules/render/HoleESP: CoordCheck 
	javafx/scene/web/WebEngine: FileDeletionCheck 
	com/sun/javafx/css/ParsedValueImpl: URLCheck 
	javafx/fxml/FXMLLoader$Element: URLCheck 
	com/sun/javafx/iio/common/ImageTools: WebConnectionCheck URLCheck 
	com/sun/javafx/font/FontFileWriter$FontTracker$TempFileDeletionHook: FileDeletionCheck 
	me/xenodevs/xeno/module/modules/combat/AutoCrystalPostman: CoordCheck 
	com/sun/webkit/network/DirectoryURLConnection$DirectoryInputStream: WebConnectionCheck 
	com/sun/javafx/tk/Toolkit: WebConnectionCheck URLCheck 
	me/xenodevs/xeno/utils/render/RenderUtils3D: CoordCheck 
	javafx/scene/Cursor: URLCheck 
	com/sun/javafx/webkit/drt/DumpRenderTree: URLCheck 
	javafx/fxml/FXMLLoader$IncludeElement: URLCheck 
	javafx/fxml/FXMLLoader$ScriptElement: WebConnectionCheck URLCheck 
	me/xenodevs/xeno/gui/GuiUtil$1: CoordCheck 
	com/sun/javafx/fxml/builder/JavaFXFontBuilder: URLCheck 
	me/xenodevs/xeno/utils/entity/EntityHelper: CoordCheck 
	com/sun/javafx/css/parser/CSSParser: WebConnectionCheck 
	com/moandjiezana/toml/StringValueReaderWriter: URLCheck 
	com/sun/javafx/application/LauncherImpl: URLCheck 
	com/sun/javafx/tk/quantum/QuantumClipboard: URLCheck 
	me/xenodevs/xeno/utils/player/PlayerUtil: CoordCheck 
	me/xenodevs/xeno/utils/entity/EntityFakePlayer: CoordCheck 
	me/xenodevs/xeno/utils/block/BlockUtil: CoordCheck 
	com/sun/javafx/PlatformUtil: URLCheck 
	me/xenodevs/xeno/utils/other/MathsHelper: CoordCheck 
	javafx/scene/text/Font: WebConnectionCheck URLCheck 
	com/sun/media/jfxmedia/locator/HLSConnectionHolder: WebConnectionCheck 
	me/wolfsurge/mixin/mixins/MixinRenderEntityItem: CoordCheck 
	com/sun/media/jfxmedia/locator/Locator: WebConnectionCheck 
	com/sun/javafx/runtime/async/AbstractRemoteResource: WebConnectionCheck URLCheck 
	com/sun/javafx/iio/ios/IosImageLoader: URLCheck 
	javafx/scene/web/WebEngine$2: WebConnectionCheck 
	javafx/scene/image/Image: URLCheck 
	com/sun/javafx/font/FontFileWriter: FileDeletionCheck 
	com/sun/javafx/font/PrismFontLoader: WebConnectionCheck 
	me/xenodevs/xeno/utils/other/RaytraceUtil: CoordCheck 
	me/xenodevs/xeno/utils/player/EnemyUtil: CoordCheck 
	com/sun/webkit/network/URLs: URLCheck 
	com/sun/javafx/css/Stylesheet: WebConnectionCheck 
	me/xenodevs/xeno/utils/combat/CrystalUtil: CoordCheck 
	com/sun/javafx/font/PrismFontFile$FileDisposer: FileDeletionCheck 
	me/xenodevs/xeno/utils/block/hole/HoleUtil: CoordCheck 
	com/sun/javafx/fxml/builder/URLBuilder: URLCheck 
	com/sun/javafx/font/PrismFontFile: FileDeletionCheck 
	javafx/fxml/FXMLLoader: WebConnectionCheck URLCheck 
	me/xenodevs/xeno/utils/block/BlockInteractionHelper: CoordCheck 
	com/sun/deploy/uitoolkit/impl/fx/HostServicesFactory$StandaloneHostService: CommandCheck 
	me/xenodevs/xeno/utils/entity/EntityUtil: CoordCheck 
	com/sun/javafx/css/converters/URLConverter: URLCheck 
	me/xenodevs/xeno/module/modules/combat/Aura: CoordCheck 
	com/sun/webkit/network/URLLoader: WebConnectionCheck 
	com/sun/webkit/LocalizedStrings$EncodingResourceBundleControl: WebConnectionCheck 
	me/xenodevs/xeno/module/modules/movement/NoFall: CoordCheck

**Comment by XenoClientDevelopment** [comment]
what the fuck did you do

**Comment by XenoClientDevelopment** [comment]
also no

**Comment by master7720** [comment]
why?

**Comment by AcaiBerii** [comment]
lol?
