### ISSUE TITLE
PASTE

### ISSUE THREAD

**Issue by linustouchtips** [XenoClientDevelopment/Xeno-Client#3]
major paste lel

**Comment by Wolfsurge** [comment]
1. not a massive paste, majority of stuff is original
2. add frame based GUI back to cosmos pls
3. blame mathew101q for most of the skidded stuff

**Comment by linustouchtips** [comment]
?

**Comment by linustouchtips** [comment]
why would you edit my comment

**Comment by Wolfsurge** [comment]
didn't know I could, then saw it and tried it. also it isnt a 'major paste', and add the frame based GUI back to cosmos pls

**Comment by linustouchtips** [comment]
it kind of is though, and also no, it doesn't allow me to have the same functionality as the window based one.

**Comment by Wolfsurge** [comment]
it honestly isnt a major paste, and you can blame mathew101q for the pasted stuff. shame about the cosmos gui tho, but oh well

**Comment by acaiberii** [comment]
![break it down bring it back make it clap](https://i.imgur.com/g0Y7PZG.png)

**Comment by Wolfsurge** [comment]
I agree with my unbiased opinion

**Comment by acaiberii** [comment]
i do not

**Comment by Wolfsurge** [comment]
cool, I respect ur opinion
